[__config__]
oldver="oldver.json"
newver="newver.json"
keyfile="keyfile.toml"

[inltk]
source="github"
github="goru001/inltk"
use_latest_tag=true

[greentunnel]
source="github"
github="sadeghhayeri/greentunnel"
use_latest_tag=true

[srsly]
source="github"
github="explosion/srsly"
use_latest_tag=true

[firebase-admin-python]
source="github"
github="firebase/firebase-admin-python"
use_latest_tag=true

[chatterbot]
source="github"
github="gunthercox/chatterbot"
use_latest_tag=true

[crfsuite]
source="github"
github="chokkan/crfsuite"
use_latest_tag=true

[pdf2docx]
source="github"
github="artifexsoftware/pdf2docx"
use_latest_tag=true

[wasabi]
source="github"
github="explosion/wasabi"
use_latest_tag=true

[mathparse]
source="github"
github="gunthercox/mathparse"
use_latest_tag=true

[curses-menu]
source="github"
github="pmbarrett314/curses-menu"
use_latest_tag=true

[firestore]
source="github"
github="googleapis/python-firestore"
use_latest_tag=true

[python-vlc]
source="pypi"
pypi="python-vlc"

[libvarnam]
source="github"
github="varnamproject/libvarnam"
use_latest_tag=true

[govarnam]
source="github"
github="varnamproject/govarnam"
use_latest_tag=true

[govarnam-ibus]
source="github"
github="varnamproject/govarnam-ibus"
use_latest_tag=true

[govarnam-schemes]
source="github"
github="varnamproject/schemes"
use_latest_tag=true

[autoscraper]
source="github"
github="alirezamika/autoscraper"
use_latest_tag=true

[metaphone]
source="github"
github="oubiwann/metaphone"
use_latest_tag=true

[git-review]
source="git"
git="https://opendev.org/opendev/git-review.git"

[dataprep]
source="github"
github="sfu-db/dataprep"
use_latest_tag=true

[varname]
source="github"
github="pwwang/python-varname"
use_latest_tag=true

[ibus-m17n]
source="github"
github="ibus/ibus-m17n"
use_latest_tag=true

[milksnake]
source="github"
github="getsentry/milksnake"
use_latest_tag=true

[split-folders]
source="github"
github="jfilter/split-folders"
use_latest_tag=true

[python-oauth2token]
source="pypi"
pypi="oauth2token"

[parserator]
source="github"
github="datamade/parserator"
use_latest_tag=true

[usaddress]
source="github"
github="datamade/usaddress"
use_latest_tag=true

[python-probableparsing]
source="pypi"
pypi="probableparsing"

[func_timeout]
source="github"
github="kata198/func_timeout"
use_latest_tag=true

[python-crfsuite]
source="github"
github="scrapinghub/python-crfsuite"
use_latest_tag=true

[python-shelved_cache]
source="github"
github="mariushelf/shelved_cache"
use_latest_tag=true

[python-tradingeconomics]
source="pypi"
pypi="tradingeconomics"

[python-wbdata]
source="github"
github="oliversherouse/wbdata"
use_latest_tag=true

[textblob]
source="github"
github="sloria/textblob"
use_latest_tag=true

[newspaper4k]
source="github"
github="andythefactory/newspaper4k"
use_latest_tag=true

[newspaper3k]
source="pypi"
pypi="newspaper3k"

[indic-nlp-library]
source="github"
github="anoopkunchukuttan/indic_nlp_library"
use_latest_tag=true
